### ISSUE TITLE
Version checking doesn't work properly on mac or windows

### ISSUE THREAD

**Issue by naslundx** [klarna-incubator/webtraversallibrary#138]
There are commands for checking this in version_check.py that only work on linux, apparently...

**Comment by naslundx** [comment]
https://stackoverflow.com/questions/50880917/how-to-get-chrome-version-using-command-prompt-in-windows

**Comment by naslundx** [comment]
Mac: /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version

**Comment by apikas** [comment]
Why not skip the browser version check completely if on Windows? I think the check was intended to make it easer to spot version mismatches, but if there is a mismatch, chromedriver will issue an error message that is understandable.

**Comment by naslundx** [comment]
It's been my experience that issues due to webdriver mismatch are actually very difficult to spot. But I'm doing this for now #158 and we can reevaluate for the next version.

**Comment by apikas** [comment]
I guess it depends on how the error handling is set up.
I just let the python script abort, and it shows near the bottom of the output e.g. if i downgrade cromedriver from 88 to 86:

`...
File "Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 86
Current browser version is 88.0.4324.150 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
`
