### ISSUE TITLE
Character encoding on saved files needed in Windows

### ISSUE THREAD

**Issue by apikas** [klarna-incubator/webtraversallibrary#140]
WTL 0.11.4

The default encoding in Windows 10 (cp1252) for Python < 3.9 may case exceptions on some pages.
Since I always want UTF-8, I patched the `open` calls in snapshot.py like so:
```(path / "source.html", "w", encoding="utf8")```

I'm not up to speed on the latest Python development, and this problem may go away in later Python versions.
See e.g. https://www.python.org/dev/peps/pep-0597/

```
  File "C:\Users\pikand\AppData\Local\Programs\Python\Python38\lib\site-packages\webtraversallibrary\snapshot.py", line 293, in save
    f.write(str(self.page_source))
  File "C:\Users\pikand\AppData\Local\Programs\Python\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 36954-36960: character maps to <undefined>
```

**Comment by naslundx** [comment]
Thank you!
