### ISSUE TITLE
version_check on Windows: FileNotFoundError

### ISSUE THREAD

**Issue by apikas** [klarna-incubator/webtraversallibrary#169]
I ran v0.12.0 on Windows 10, and got an exception that was not caught in version_check.py, line 28: FileNotFoundError.
I fixed it like this:
`    except (CalledProcessError, FileNotFoundError):`

All other Windows issues that I had in 0.11 seem to have been fixed 🥇

**Comment by vonNiklasson** [comment]
Thank you @apikas for the issue report and the fix/workaround, I will look into this as soon as I get hold on a Windows computer :)

Cheers
Johan

**Comment by vonNiklasson** [comment]
Hello again @apikas!

I'm just letting you know that the issue is fixed and will be shipped in next version (`0.13.0`) which will be released later today 🎉
