### ISSUE TITLE
No index page on GitHub pages

### ISSUE THREAD

**Issue by vonNiklasson** [klarna-incubator/webtraversallibrary#60]
When opening [GitHub pages](https://klarna-incubator.github.io/webtraversallibrary/) for Web Traversal Library, you're met with a `404`, since no `index` file seems to be generated. You can however open [gettingstarted.html](https://klarna-incubator.github.io/webtraversallibrary/gettingstarted.html) for instance if you type in the file name.

I assume the docs are not pushed because of this [commented section](https://github.com/klarna-incubator/webtraversallibrary/blob/master/.github/workflows/build.yml#L45)?

**Comment by vonNiklasson** [comment]
I haven't been able to troubleshoot more than building the docs locally and could see that an index file is generated.

But I noticed that the `source-directory` attribute on the [Build workflow](https://github.com/klarna-incubator/webtraversallibrary/blob/master/.github/workflows/build.yml#L50) might be wrong, as locally it's generated as `docs/_build/html` instead of `docs/build`.

**Comment by naslundx** [comment]
Thanks for the issue! I'm not sure what should happen here. I was trying out some different options for publishing the docs. They're currently being published here: https://webtraversallibrary.readthedocs.io/en/latest/

Do you have any suggestion on what is best?

**Comment by vonNiklasson** [comment]
Ah, you're right. I think that's for pushing the docs to readthedocs.io, not for GitHub pages.

I guess it depends on if you want to keep the GitHub pages since it would only mirror the readthedocs.io anyway, so possibly disable the GitHub pages if they aren't necessary?

**Comment by naslundx** [comment]
The internal suggestion (not requirement) was to use GH pages. The problem was to have it support all existing versions, and not just the master docs. If you know how to do that, you're a :star:

**Comment by robinpokorny** [comment]
Since the docs have to be generated (except for the getting started), I'd suggest disabling GitHub Pages and linking to the readthedocs.io in the project details.

**Comment by naslundx** [comment]
Let's remove GH pages
